name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'

    outputs:
      should_skip: ${{ steps.check_skip.outputs.skip }}

    steps:
      - uses: actions/checkout@v3

      - name: Check if should skip
        id: check_skip
        run: |
          if [[ "${{ join(github.event.commits.*.message, ' ') }}" == *"#skip"* ]]; then
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Trigger deployment to Render
        if: steps.check_skip.outputs.skip == 'false'
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}

      - name: Notify Discord of failure
        if: failure()
        uses: Ilshidur/action-discord@master
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: |
            🚨 Deploy failed!
            Repo: ${{ github.repository }}
            Commit: ${{ github.sha }}
            Message: ${{ github.event.head_commit.message }}
            Author: ${{ github.actor }}

      - name: Notify Discord of success
        if: success()
        uses: Ilshidur/action-discord@master
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: |
            ✅ Deploy succeeded!
            Repo: ${{ github.repository }}
            Commit: ${{ github.sha }}
            Author: ${{ github.actor }}

  tag_release:
    needs: deploy
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && needs.deploy.outputs.should_skip == 'false'

    steps:
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
